### ISSUE TITLE
Remove Unused SQL

### ISSUE THREAD

**Issue by fribeiro1** [maltron/Porcupine#1]
Several objects from [Saruman](https://github.com/maltron/saruman) that were added to the `server/javaee/7/porcupine/authorization_server/create-database.sql` file by mistake need to be removed

**Comment by maltron** [comment]
Agree. However, this particular file I added in very early days at the beginning at the project and I am pretty sure I am no longer needed that. The whole schema will be created automatically, once the Authorization Server is deployed in a Java EE 7 container. I will make sure I will remove this file. Thanks.

**Comment by fribeiro1** [comment]
Thanks!
